use strict;
use warnings;
use Transposome::SeqFactory;

use Test::More 'no_plan';

my $seq_num = 1;
my $seqio   = Transposome::SeqFactory->new( fh => \*DATA, format => 'fastq' )->make_seqio_object;

while ( my $seq = $seqio->next_seq ) {
    ok( $seq->has_id,  "Can read from filehandle - Fastq sequence $seq_num has an ID" );
    ok( $seq->has_seq, "Can read from filehandle - Fastq sequence $seq_num has a sequence" );
    ok( $seq->has_qual,
	"Can read from filehanle - Fastq sequence $seq_num has quality scores" );
        $seq_num++;
}

__DATA__
@HWI-ST766:139:D13WEACXX:3:1101:1210:2183 1:N:0:GATCAG
CTAGCACTCCTACAAAATTCATCCACCACACAGGCTCACGAAATTGCTCTCTCTCTCTAAACTCTGATTTCTAATTTCAAGTGCTTAACCCTAACCCTAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@HWI-ST766:139:D13WEACXX:3:1101:1296:2221 1:N:0:GATCAG
GGGTCGGTGATACATAGTACTTCGACCCTGGGTATAAGTGCGGTAGTAATACTCCAATTCAGACAACCCAGGCTGAATTGGAGGCCCATCATAACCCGCA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@HWI-ST766:139:D13WEACXX:3:1101:1399:2247 1:N:0:GATCAG
ATCTATATCTATAAAAGTATTTTTTTTTGTATGATTTATAACCTGATATCTTTTCATGCTTAGACCCATGTTTGGCAAACCTTACCAAGAACGGAAAAAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@HWI-ST765:123:D0TEDACXX:5:1101:2872:2088/1
TTGTCTTCCAGATAATTCCGCTATGTTCAACAAATATGTTAGATTCAAGTTTTTCTTGATAAACCTATTTAAAACCATGA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@HWI-ST765:123:D0TEDACXX:5:1101:2872:2088/2
AACTGATTCAATCGATTCAATATTGTGTTATAAAGTTTATTTCTATTTCCGTTGCAACTTAAATCTGATTTACATTCATT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
