name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.30' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: sudo apt install -y build-essential lib32z1 git ncbi-blast+ curl
      - run: perl -V
      - run: cpanm --installdeps .
      - run: perl Makefile.PL && make
      - run: prove -lv t
   codecov:
     runs-on: ubuntu-latest
     container: perl:latest
     steps:
       - uses: actions/checkout@v2
       - name: Run codecov GitHub Action
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         run: |
           cpanm --quiet --notest Module::Build Devel::Cover Devel::Cover::Report::Codecovbash
           cover -test -report codecov

